bag = Bag.create()

wishbone = Item.create([{ name: 'Wishbone',                   description: 'Just a bone.',                        image: 'wishbone.jpg',  bag: bag}])
marble   = Item.create([{ name: 'Marble',                     description: 'Much shiny, very round.',             image: 'marble.jpg',    bag: bag}])
pennies  = Item.create([{ name: 'Pennies',                    description: 'A whopping 4 of them.',               image: '4pen.jpg',      bag: bag}])
shilling = Item.create([{ name: 'Shilling',                   description: 'Worth 5 pennies.',                    image: 'shilling.jpg',  bag: bag}])
weapon1  = Item.create([{ name: 'Excalibur',                  description: 'The legendary sword of King Arthur',  image: 'Sword1.jpg',    bag: bag}])
helm1    = Item.create([{ name: 'Helm of the Divine War',     description: 'Worn by the forgotten king',          image: 'helm1.jpg',     bag: bag}])
chest1   = Item.create([{ name: 'Greatplate of Burning Wars', description: 'Worn on the battlefield',             image: 'chest1.jpeg',   bag: bag}])
legs1    = Item.create([{ name: 'Flamewaker Legplates',       description: 'Fiery legplates',                     image: 'legs1.jpeg',    bag: bag}])
bow1     = Item.create([{ name: 'Fire Bow',                   description: 'A bow from Robin Hood',               image: 'bow1.jpeg',     bag: bag}])
axe1     = Item.create([{ name: 'War Axe',                    description: 'It is a big axe',                     image: 'axe1.jpeg',     bag: bag}])
